export const CODE_RAR = {
  TOKEN_EXPIRED: 'TOKEN_EXPIRED'
}

export const MESSAGE_RAR = {
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  UNAUTHORIZED: 'UNAUTHORIZED'
}

export const TITLE_RAR = {
  ERROR: 'ERROR'
}
